spring.datasource.url=jdbc:postgresql://ep-autumn-brook-an5y0jv1-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_GV25AosXpTBL&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update
spring.freemarker.enabled=true
spring.freemarker.suffix=.ftlh
server.port=9090

#Log out sql queries or comment these lines out with a hashtag
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE